services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: adamic_llm:${ADAMIC_LLM_VERSION:-latest}
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ADAMIC_LLM_HOST: 0.0.0.0
      ADAMIC_LLM_DB_HOST: adamic_llm-db
      ADAMIC_LLM_DB_PORT: 5432
      ADAMIC_LLM_DB_USER: adamic_llm
      ADAMIC_LLM_DB_PASS: adamic_llm
      ADAMIC_LLM_DB_BASE: adamic_llm
      ADAMIC_LLM_REDIS_HOST: adamic_llm-redis
      ADAMIC_LLM_LLM_PROVIDER: ${ADAMIC_LLM_LLM_PROVIDER}
      ADAMIC_LLM_GROQ_API_KEY: ${ADAMIC_LLM_GROQ_API_KEY}
      ADAMIC_LLM_GROQ_LLM: ${ADAMIC_LLM_GROQ_LLM}
      ADAMIC_LLM_GROQ_API_BASE: ${ADAMIC_LLM_GROQ_API_BASE}
      ADAMIC_LLM_GOOGLE_PROJECT_ID: ${ADAMIC_LLM_GOOGLE_PROJECT_ID}
      ADAMIC_LLM_GOOGLE_APPLICATION_CREDENTIALS: ${ADAMIC_LLM_GOOGLE_APPLICATION_CREDENTIALS}
      ADAMIC_LLM_OPENROUTER_API_KEY: ${ADAMIC_LLM_OPENROUTER_API_KEY}
      ADAMIC_LLM_ENABLE_LANGFUSE: ${ADAMIC_LLM_ENABLE_LANGFUSE:-False}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_HOST: ${LANGFUSE_HOST}
    volumes:
      - /home/jens/.config/gcloud/application_default_credentials.json:/app/application_default_credentials.json:ro

  db:
    image: postgres:18.1-bookworm
    hostname: adamic_llm-db
    environment:
      POSTGRES_PASSWORD: "adamic_llm"
      POSTGRES_USER: "adamic_llm"
      POSTGRES_DB: "adamic_llm"
    volumes:
      - adamic_llm-db-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: pg_isready -U adamic_llm
      interval: 2s
      timeout: 3s
      retries: 40

  redis:
    image: redis:8.4.0
    hostname: "adamic_llm-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
  
  #open-webui:
  #  container_name: open-webui
  #  image: ghcr.io/open-webui/open-webui:latest
  #  restart: "no"
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - ./docker/volumes/open-webui:/app/backend/data
  #  environment:
  #    - ENABLE_OLLAMA_API=false
  #    - USE_OLLAMA_DOCKER=false
  #    - ENABLE_IMAGE_GENERATION=false
  #    - ENABLE_TAGS_GENERATION=false
  #    #### OPENAI API ####
  #    - OPENAI_API_BASE_URL=http://127.0.0.1:8000/v1
  #    - OPENAI_API_KEY=DUMMY



volumes:
  adamic_llm-db-data:
    name: adamic_llm-db-data
